export const SET_MATCHES = 'SET_MATCHES';
export const ADD_TO_BASKET = 'ADD_TO_BASKET';
export const REMOVE_FROM_BASKET = 'REMOVE_FROM_BASKET';
export const SET_USER_DETAILS = 'SET_USER_DETAILS';
export const CLEAR_BASKET = 'CLEAR_BASKET';
export const SET_SOCKET = 'SET_SOCKET';
